import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  contenedorCentrado: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contenedor: {
    flex: 1,
    padding: 20,
  },
  scrollContent: {
    paddingVertical: 20,
  },
  seccion: {
    marginBottom: 20,
  },
  seccionEspaciada: {
    marginTop: 30,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subLabel: {
    fontSize: 14,
    color: '#555',
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 16,
    marginBottom: 10,
  },
  errorText: {
    color: 'red',
    textAlign: 'center',
    marginBottom: 6,
  },
  indicadorGuardado: {
    marginTop: 10,
  },
    safeArea: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  contenedor: {
    flex: 1,
    padding: 20,
    backgroundColor: '#fff',
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  resumenValores: {
    marginBottom: 30,
  },
  filaValor: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  etiqueta: {
    fontSize: 18,
    color: '#555',
  },
  valor: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  seccionesParalelas: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  seccionBoton: {
    flex: 1,
    backgroundColor: '#007bff',
    paddingVertical: 14,
    marginHorizontal: 5,
    borderRadius: 8,
    alignItems: 'center',
  },
  seccionTexto: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  botonCircularL: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    flexDirection: 'row',
    gap: 15,
  },
  botonCircular: {
    backgroundColor: '#28a745',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
    elevation: 5, // sombra para Android
    shadowColor: '#000', // sombra para iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  botonCircularR: {
    backgroundColor: '#007bff',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5, // sombra para Android
    shadowColor: '#000', // sombra para iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  contenedor: {
    flex: 1,
    padding: 20,
    backgroundColor: '#fff',
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  resumenValores: {
    marginBottom: 30,
  },
  filaValor: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  etiqueta: {
    fontSize: 18,
    color: '#555',
  },
  valor: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  seccionesParalelas: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  seccionBoton: {
    flex: 1,
    backgroundColor: '#007bff',
    paddingVertical: 14,
    marginHorizontal: 5,
    borderRadius: 8,
    alignItems: 'center',
  },
  seccionTexto: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  botonCircularL: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    flexDirection: 'row',
    gap: 15,
  },
  botonCircular: {
    backgroundColor: '#28a745',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
    elevation: 5, // sombra para Android
    shadowColor: '#000', // sombra para iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  botonCircularR: {
    backgroundColor: '#007bff',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5, // sombra para Android
    shadowColor: '#000', // sombra para iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  contenedorPrincipal: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingTop: 15,
  },
  contenedorCentrado: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoVacio: {
    fontSize: 18,
    color: '#666',
    textAlign: 'center',
    marginVertical: 6,
  },
  lista: {
    marginTop: 10,
  },
  itemContainer: {
    backgroundColor: '#f0f0f0',
    padding: 15,
    borderRadius: 8,
    marginBottom: 12,
  },
  itemNombre: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  itemDescripcion: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  botonFlotante: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: '#007bff',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5, // sombra Android
    shadowColor: '#000', // sombra iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  botonFlotanteTexto: {
    fontSize: 36,
    color: '#fff',
    lineHeight: 36,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#007bff',
  },
  errorText: {
    fontSize: 16,
    color: '#dc3545',
    textAlign: 'center',
    marginBottom: 15,
  },
  titulo: {
    fontSize: 26,
    fontWeight: 'bold',
    marginVertical: 15,
    textAlign: 'center',
    color: '#222',
  },
  descripcion: {
    fontSize: 16,
    color: '#444',
    marginBottom: 12,
    textAlign: 'center',
  },
  label: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
    color: '#333',
    textAlign: 'left',
  },
  separador: {
    height: 1,
    backgroundColor: '#ccc',
    marginVertical: 15,
  },
  participantesContainer: {
    marginBottom: 15,
  },
  participanteItem: {
    fontSize: 15,
    color: '#555',
    paddingVertical: 3,
  },
  noParticipantes: {
    fontSize: 15,
    color: '#999',
    fontStyle: 'italic',
    marginBottom: 15,
  },
  botonesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  botonWrapper: {
    flex: 1,
    marginHorizontal: 5,
  },
  botonCircular: {
    backgroundColor: '#007bff',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  gastoItem: {
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  statusText: {
    marginTop: 10,
    fontSize: 16,
    color: '#007bff',
    textAlign: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#dc3545',
    textAlign: 'center',
    marginBottom: 15,
  },
  kavContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollViewContainer: {
    paddingHorizontal: 20,
  },
  scrollViewContent: {
    paddingBottom: 40,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginTop: 15,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  textArea: {
    height: 90,
    textAlignVertical: 'top',
  },
  buttonContainer: {
    marginTop: 20,
    marginBottom: 10,
  },
  submitIndicator: {
    marginTop: 10,
  },
  seleccionadosContainer: {
    marginTop: 25,
  },
  seleccionadosLabel: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 8,
    color: '#222',
  },
  seleccionadosWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  participanteSeleccionado: {
    backgroundColor: '#007bff',
    borderRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  participanteTexto: {
    color: '#fff',
    fontWeight: '600',
  },
  placeholderTextPequeño: {
    fontStyle: 'italic',
    fontSize: 14,
    color: '#999',
  },
  listaContactosScrollView: {
    marginTop: 10,
    maxHeight: 220,
  },
  emptyListContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  placeholderText: {
    color: '#999',
    fontStyle: 'italic',
    fontSize: 15,
  },
  contactoItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
  },
  contactoNombre: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
  },
  contactoNumero: {
    fontSize: 14,
    color: '#555',
  },
  contactoSeleccionado: {
    backgroundColor: '#d0e7ff',
  },
  contenedorCentradoPermisoDenegado: {
    marginTop: 25,
    alignItems: 'center',
  },
  ModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)', // Fondo semitransparente
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  Modalcontent: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5, // para Android
  },
  Modaltitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 15,
    color: '#333',
    textAlign: 'center',
  },
  ModalInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 15,
    backgroundColor: '#fafafa',
  },
  kavContainer: {
    flex: 1,
    backgroundColor: '#f0f4f8',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  container: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '700',
    color: '#007bff',
    marginBottom: 25,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: '#fafafa',
  },
  spinner: {
    marginVertical: 20,
  },
  enlace: {
    marginTop: 15,
    color: '#007bff',
    textAlign: 'center',
    fontWeight: '600',
  },
  enlaceDeshabilitado: {
    color: '#a0a0a0',
  },
  kavContainer: {
    flex: 1,
    backgroundColor: '#f0f4f8',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  container: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '700',
    color: '#007bff',
    marginBottom: 25,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: '#fafafa',
  },
  spinner: {
    marginVertical: 20,
  },
  enlace: {
    marginTop: 15,
    color: '#007bff',
    textAlign: 'center',
    fontWeight: '600',
  },
  enlaceDeshabilitado: {
    color: '#a0a0a0',
  },
});
